### PR TITLE
Add tvOS support

### PR DESCRIPTION
**Pull request by thomasjoulin**

### CODE REVIEW

**Comment by gavineadie** [comment]
Done ..

**Comment by thomasjoulin** [comment]
@gavineadie thanks! could you tag a release so we don't have to point to master on Cocoapods? 🙏

**Comment by gavineadie** [comment]
done ..

**Comment by thomasjoulin** [comment]
@gavineadie sorry to disturb again but it seems the specs are not published. Searching for ios-ntp on Cocoapods leads to:

```
-> ios-ntp (1.1.1)
   SNTP implementation for iOS.
   pod 'ios-ntp', '~> 1.1.1'
   - Homepage: https://github.com/jbenet/ios-ntp
   - Source:   https://github.com/jbenet/ios-ntp.git
   - Versions: 1.1.1, 1.1, 1.0.1, 1.0.0 [master repo]
```

**Comment by gavineadie** [comment]
Yipes!  That was last updated in 2014 and it appears multiple things have changed in the infrastructure since then.  I don't use CocoaPods so I'm somewhat at a loss where to start.  My first attempt was rejected because of a tangential dependence (which isn't actually relevant any more).  So, forgive me while I research how to do this and try and get it right.  I'll try again overnight US time.

**Pull request merged**
