### PR TITLE
Segregated cocoaasyncsocket

### PR DESCRIPTION
**Pull request by pakistancan**
There was a conflict when using cocoasyncsocket and ios-ntp, just added pod dependency and removed files asyncsocket files form network-lib

### CODE REVIEW

**Comment by pakistancan** [comment]
@jbenet Please merge this

**Comment by pakistancan** [comment]
Thanks, can you please also push it to cocoa pods?

**Comment by gavineadie** [comment]
Done? I'm not a CocoaPods user so please check it's OK.

**Comment by pakistancan** [comment]
@gavineadie It is not pushed yet, cocoapods is still showing 1.1.8

When I tried to push 1.1.9 from my machine it says 
"You are not allowed to push new versions for this pod. The owners of this pod are gavineadie@mac.com"

Please try to push it using following command 

pod trunk push ios-ntp.podspec --allow-warnings

**Comment by gavineadie** [comment]
There is a warning with a tvOS usage in `CocoaAsyncSocket:

     -> ios-ntp (1.1.9)
        - WARN  | [tvOS] xcodebuild:  
        CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m:8113:72: 
        warning: 'kCFStreamNetworkServiceTypeVoIP' is deprecated: first deprecated in tvOS 9.0
    ...
but the push completed:

    ios-ntp (1.1.9) successfully published
    June 7th, 11:02
    https://cocoapods.org/pods/ios-ntp
    Tell your friends!

**Comment by pakistancan** [comment]
Thanks 👍

**Pull request merged**
